apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: db
  name: db
spec:
  containers:
    - image: postgres
      name: pg
      ports:
        - containerPort: 5432
          protocol: TCP
      tty: true
      env:
        - name: POSTGRES_USER
          value: cnrprod1725729288-team-77382
        - name: POSTGRES_PASSWORD
          value: cnrprod1725729288-team-77382
  restartPolicy: OnFailure