openapi: "3.0.0"
info:
  version: 1.0.0
  title: Tender API

paths:
  /api/ping:
    get:
      summary: "Get a pong response"
      operationId: getPing
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PongResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    PongResponse:
      type: object
      properties:
        message:
          type: string
          example: "pong"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message